title: "社内勉強会Reactアプリの開発ガイド"
summary: |
       社内勉強会向けのReact(Js)アプリ開発ガイドです。
       想定読者はまず「React?」くらいの初心者です。
       開発ガイドといいつつ、ハンズオンのチュートリアルから始めていきます。
       作者も初心者であるため誤り・ご指摘あればフィードバックいただければとありがたいです。
topics: ["react", "Javascript"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - about_react
