title: "社内勉強会Reactアプリの開発ガイド"
summary: |
       社内勉強会向けのReact(Js)アプリ開発ガイドです。
       想定読者はまず「Reactが何かわからない」くらいの初心者です。
       誤り・ご指摘あればフィードバックいただければとありがたいです。
topics: ["react", "Javascript"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 1_first
  - 2_about_react
  - 3_create_page
